# Generated by Django 3.2 on 2022-06-22 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Realtor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('photo', models.ImageField(upload_to='photos/%Y/%m/%d')),
                ('description', models.TextField(blank=True)),
                ('phone_number', models.CharField(max_length=13)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('is_mvp', models.BooleanField(default=False)),
                ('hire_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
