# Generated by Django 3.2 on 2022-06-23 04:04

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('realtors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realtor',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(help_text='Contact phone number', max_length=31),
        ),
    ]
