# Generated by Django 3.2 on 2022-06-23 11:24

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('realtors', '0003_alter_realtor_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realtor',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
    ]
